question 3. four people have been found to match the criteria specified

In [1]:
# !pip install textblob
# !pip install spacy
# !python -m spacy download en_core_web_lg

In [2]:
import json
import os
import pandas as pd
import ast
import time
from textblob import TextBlob
import re
import spacy
nlp = spacy.load('en_core_web_lg')
pd.options.display.max_columns = None

In [3]:
df_user=pd.read_csv("./data/user.csv")

In [4]:
df_review=pd.read_csv("./data/review.csv")

/home/ubuntu/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2728: DtypeWarning: Columns (0,2) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [5]:
df_business=pd.read_csv("./data/business.csv")

In [6]:
df_review.head(1)

,Unnamed: 0,business_id,cool,date,funny,review_id,stars,text,useful,user_id
0,0,iCQpiavjjPzJ5_3gPD5Ebg,0,2011-02-25,0.0,x7mDIiDB3jEiPGPHOmDzyw,2.0,The pizza was okay. Not the best I've had. I p...,0.0,msQe1u7Z_XuqjGoqhB0J5g

In [7]:
# join 
df_review =df_review.merge(df_business,on="business_id")

In [8]:
review_last_year =df_review[(df_review['date'] > '2017-1-1 01:00:00') & (df_review['date'] <= '2018-1-1 04:00:00')]

In [9]:
review_canada = review_last_year.loc[review_last_year.postal_code.str.len()==7].reset_index()
review_canada_agg = review_canada.groupby(['user_id']).count().reset_index()
review_canada_agg = review_canada_agg.sort_values(by=['index'],ascending=False)
review_canada_agg = review_canada_agg[review_canada_agg['index']>=10]

In [10]:
review_mon = review_last_year.loc[review_last_year['name']=="Mon Ami Gabi"]

In [11]:
review_mon_canadian =review_mon.merge(review_canada_agg,on="user_id")

In [12]:
# my analysis yield four canadian that flew over to las vegas to review this restaurant
review_mon_canadian.head(1)

,Unnamed: 0_x_x,business_id_x,cool_x,date_x,funny_x,review_id_x,stars_x_x,text_x,useful_x,user_id,Unnamed: 0_y_x,address_x,attributes_x,categories_x,city_x,hours_x,is_open_x,latitude_x,longitude_x,name_x,neighborhood_x,postal_code_x,review_count_x,stars_y_x,state_x,index,Unnamed: 0_x_y,business_id_y,cool_y,date_y,funny_y,review_id_y,stars_x_y,text_y,useful_y,Unnamed: 0_y_y,address_y,attributes_y,categories_y,city_y,hours_y,is_open_y,latitude_y,longitude_y,name_y,neighborhood_y,postal_code_y,review_count_y,stars_y_y,state_y
0,1542486,4JNXUYY8wbaaDmk3BPzlWw,0,2018-02-12,0.0,silBrMr5LUHNibxCtIk_6Q,3.0,Just passing by and decided to stop here for l...,0.0,UMVPoZ5YYewEmVZLBPpXSg,137635,3655 Las Vegas Blvd S,"{'Alcohol': 'full_bar', 'Ambience': ""{'romanti...","Steakhouses, Breakfast & Brunch, Restaurants, ...",Las Vegas,"{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ...",1,36.112827,-115.172581,Mon Ami Gabi,The Strip,89109,7968,4.0,NV,40,40,40,40,40,40,40,40,40,40,40,40,40,40,40,35,40,40,40,40,29,40,40,40,40

Question # 5  five people have been found to match the criteria specified

In [13]:
# Find  users from Ontario who have left more than 10 reviews.
review_on = df_review.loc[df_review['state']=="ON"]
review_on_agg = review_on.groupby(['user_id']).count().reset_index()
review_on_agg = review_on_agg.sort_values(by=['state'],ascending=False)
review_on_agg = review_on_agg[review_on_agg['state']>=10]

In [14]:
review_mon = df_review.loc[df_review['name']=="Mon Ami Gabi"]

In [15]:
review_ontario10_mon =review_mon.merge(review_on_agg,on="user_id").head()

In [19]:
review_ontario10_mon

,Unnamed: 0_x_x,business_id_x,cool_x,date_x,funny_x,review_id_x,stars_x_x,text_x,useful_x,user_id,Unnamed: 0_y_x,address_x,attributes_x,categories_x,city_x,hours_x,is_open_x,latitude_x,longitude_x,name_x,neighborhood_x,postal_code_x,review_count_x,stars_y_x,state_x,Unnamed: 0_x_y,business_id_y,cool_y,date_y,funny_y,review_id_y,stars_x_y,text_y,useful_y,Unnamed: 0_y_y,address_y,attributes_y,categories_y,city_y,hours_y,is_open_y,latitude_y,longitude_y,name_y,neighborhood_y,postal_code_y,review_count_y,stars_y_y,state_y
0,126216,4JNXUYY8wbaaDmk3BPzlWw,1,2014-05-28,1.0,_hk8WTOtpD6b9dW_4-RpcA,4.0,Lovely nook in the Parisian hotel. The outdoor...,1.0,rp10AQdPM9MIxNzxj6SOZw,137635,3655 Las Vegas Blvd S,"{'Alcohol': 'full_bar', 'Ambience': ""{'romanti...","Steakhouses, Breakfast & Brunch, Restaurants, ...",Las Vegas,"{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ...",1,36.112827,-115.172581,Mon Ami Gabi,The Strip,89109,7968,4.0,NV,60,60,60,60,60,60,60,60,60,60,60,60,60,60,53,60,60,60,60,54,60,60,60,60
1,487981,4JNXUYY8wbaaDmk3BPzlWw,0,2015-11-11,0.0,BKEHQhbJm4gG4X2GXRl4Ag,4.0,Came here for breakfast and it was easily one ...,0.0,dmF_RNlXyiY5KhsaBVvScQ,137635,3655 Las Vegas Blvd S,"{'Alcohol': 'full_bar', 'Ambience': ""{'romanti...","Steakhouses, Breakfast & Brunch, Restaurants, ...",Las Vegas,"{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ...",1,36.112827,-115.172581,Mon Ami Gabi,The Strip,89109,7968,4.0,NV,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,19,15,19,19,19,19
2,1013163,4JNXUYY8wbaaDmk3BPzlWw,1,2016-09-27,1.0,fOdj5AyG1VIJSUTHo9XTJw,5.0,Mon Ami Gabi seems like a tourist trap when yo...,2.0,GNZE2VP4I2OsAu2D2PKhqg,137635,3655 Las Vegas Blvd S,"{'Alcohol': 'full_bar', 'Ambience': ""{'romanti...","Steakhouses, Breakfast & Brunch, Restaurants, ...",Las Vegas,"{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ...",1,36.112827,-115.172581,Mon Ami Gabi,The Strip,89109,7968,4.0,NV,25,25,25,25,25,25,25,25,25,25,25,24,25,25,19,25,25,25,25,23,25,25,25,25
3,1032520,4JNXUYY8wbaaDmk3BPzlWw,0,2016-01-31,0.0,8S-h_hFpAr72i3HVT22BNA,3.0,"Average breakfast, tourist restaurant in front...",0.0,56_DKQpK4tT0rWLt4-DZOQ,137635,3655 Las Vegas Blvd S,"{'Alcohol': 'full_bar', 'Ambience': ""{'romanti...","Steakhouses, Breakfast & Brunch, Restaurants, ...",Las Vegas,"{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ...",1,36.112827,-115.172581,Mon Ami Gabi,The Strip,89109,7968,4.0,NV,87,87,87,87,87,87,87,87,87,87,85,85,87,87,77,87,87,87,87,55,86,87,87,87
4,1150064,4JNXUYY8wbaaDmk3BPzlWw,4,2018-01-28,3.0,WO6Tp5d8eI09GI49luPZyg,5.0,"Perfect, again.\n\nCame back here with friends...",5.0,YMYb73K3Dv3oiac4mADJSg,137635,3655 Las Vegas Blvd S,"{'Alcohol': 'full_bar', 'Ambience': ""{'romanti...","Steakhouses, Breakfast & Brunch, Restaurants, ...",Las Vegas,"{'Monday': '7:0-23:0', 'Tuesday': '7:0-23:0', ...",1,36.112827,-115.172581,Mon Ami Gabi,The Strip,89109,7968,4.0,NV,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15,15